# Gas Laws {#sec-gas-laws}

## Objectives

-   Explain Boyle’s Law, Charles’ Law, and the General Gas Law and use these to calculate pressure, temperature and/or volume changes for perfect gases.
-   Explain the Characteristic Gas Constant and use the Characteristic Gas Equation to determine the mass, the conditions, and the constant for a gas.
-   Explain isothermal, adiabatic, and polytropic processes (expansion and compression) for a gas, state the formula for each process, and compare the processes on a pressure/volume diagram


A perfect gas may be defined as a gas that remains in its gaseous state during changes in condition. Another way to state this is that the gas will not condense (even partially) if any of its conditions (temperature, volume or pressure) are changed.

Gases such as nitrogen, oxygen, and dry air can usually be treated as perfect gases. However, saturated steam is not considered a perfect gas, since it may condense under normal operating conditions. Although it is not technically a perfect gas, superheated steam, provided it never drops to the saturation temperature, does approximately act as a perfect gas.

For a perfect gas in a closed environment, there are specific relationships that exist between the temperature, pressure and volume of the gas. Furthermore, when any of these three conditions changes, the relationships between them can be used to predict and calculate the changes in the other conditions. For example, if the pressure and temperature change, it is possible to calculate what the change in pressure will be, and so on.

The relationships between pressure, temperature and volume have been proven by experimentation and have been described in three basic laws, called Laws of Perfect Gases. These laws are Boyle’s Law, Charles’ Laws, and the General Gas Law.

## Boyle's Law

A physicist, Robert Boyle (1627-1691), investigated the behavior of a perfect gas at a constant temperature. By removing or adding heat during a controlled change in the volume and pressure of a confined gas, he was able to hold the temperature constant. He discovered that, under this condition, the absolute pressure of a gas varies inversely with the volume. That is, if the volume increases, then the pressure decreases and, conversely, if the volume decreases, then the pressure increases. This can be stated as:\\index{Boyle's Law}

$$
P\propto\frac{1}{V}
$$ {#eq-boyle}

## Classwork

## Problem Set

## Further Reading

Read Chapter 5 in @russell2022, for additional information.
