# Heat Transfer {#sec-heat-transfer}

## Objectives

-   Explain the methods of heat transfer: conduction, convection, and radiation.
-   Define thermal conductivity and calculate the quantity of heat conducted, the temperature difference, or the material thickness when heat is transferred through flat walls and plates.

## Conduction

This method involves the flow of heat from molecule to molecule within a single solid object or from the molecules of one object to those of another object when the two are in direct contact. Molecules at a high temperature are in rapid vibration and this vibration is transferred, through molecular collision, to adjacent molecules within the same body. This causes the adjacent molecules to vibrate faster, thus increasing the temperature.

This vibration transfer, and subsequent heat transfer, will also occur between the molecules of two different objects (or substances). If one object is at a higher temperature its molecules will be vibrating faster than those of the second object. Upon contact, the vibration energy will be passed to the second object, resulting in a transfer of heat and a temperature increase in the second object.

An example of conduction\index{Conduction} is an iron bar having one end in contact with a flame. The other end will soon become hot due to the conduction of heat from molecule to molecule through the iron.

$$
Q=\frac{kAt\Delta T}{s}
$$ {#eq-conduction}

## Convection

Heat transfer by convection involves the movement of a fluid (ie. a liquid or a gas). When a fluid is in contact with a hotter surface, the fluid near that surface will be heated, causing the fluid to expand and its density to decrease. Cooler, denser fluid will displace the heated fluid and will, in turn, become heated. This continuing process of heat transfer establishes a circulation of fluid (called a convection current), which then carries heat throughout the fluid.

One example involves water in a boiler, which is heated by means of convection currents. The part of the water in contact with the hot tube walls or shell will be heated and will be displaced by cooler water, which in turn is heated and displaced.

Likewise, hot gases rising in a boiler stack, air rising from a room radiator, water heated in a heat exchanger and rising into a storage tank are all examples of convection. These are examples of natural convection, in which the fluid motion is created without the use of mechanical devices.

If fluid movement is created by a pump or a fan, heat is being transferred by forced convection. Examples are a pump circulating hot water through a building heating system, a fan forcing air through an automobile radiator, or a forced draft fan pushing hot gases through a boiler.

## Radiation

Heat transfer by radiation involves the transmission of electromagnetic waves. All bodies emit these waves and the higher the body's temperature the greater will be the emission. These waves are similar to light waves in they travel in straight lines and are able to pass through a vacuum. When they strike another body they are absorbed, reflected, or transmitted through, depending upon the material of the body. If the waves are absorbed by a body, the waves will increase the molecular activity of the body, thus creating an increase in temperature.

The condition of a body's surface will determine the amount that is absorbed or reflected. A black, rough surface will readily absorb the radiant energy. A smooth, highly polished surface will reflect most of the radiant energy. Some substances, such as air, will absorb a small portion of the radiant energy, but will permit the majority of the energy to pass through.

A typical example of radiation is heat reaching the earth from the sun. The energy waves first pass through the vacuum above the earth's atmosphere and then through the atmosphere itself where a portion is absorbed. Upon striking the earth's surface the remaining energy is absorbed and converted to heat.

In a steam boiler, radiation occurs in the furnace. Any heating surfaces that are directly exposed to the furnace will receive heat directly by radiation from the flame. These include the waterwalls and some generating tubes of a watertube boiler, radiant superheater tubes (located at the outlet of the furnace), and the furnace walls of a firetube boiler.

## Classwork

## Problem Set

## Further Reading

Read Chapter 4 in @russell2022, for additional information.
